# Case Study: Student Performance Analysis with Linear Algebra

## Step by Step Analysis

## Question 3.1
student_scores = ([[80, 70, 90],
       [60, 85, 75],
       [95, 88, 92],
       [70, 60, 65]])

## Question 3.2 Total Scores per Student (Vector Addition)
Total_score_for_student1 = 80+70+90 = 240

Total_score_for_student2 = 60+85+75 = 220

Total_score_for_student3 = 95+88+92 = 275

Total_score_for_student4 = 70+60+65 = 195

## Question 3.3 Applying Weights (Scalar Multiplication)
weight = 2
math_scores = ([80], [60], [95], [70])

weighted_math_scores = 2*([80], [60], [95], [70])

= ([[160],
       [120],
       [190],
       [140]])
       

## Question 3.4 Average Score per Subject (Matrix Operation)

In [1]:
import numpy as np

In [33]:
weight = 2
math_scores = np.array([[80], [60], [95], [70]])
math_scores.shape
final = np.dot(weight, math_scores)
final

array([[160],
       [120],
       [190],
       [140]])

In [ ]:
# weight = np.array([[2, 1, 1, 1]])
# student_scores = np.array([[80, 70, 90],
#        [60, 85, 75],
#        [95, 88, 92],
#        [70, 60, 65]])
# weight.shape
# # student_scores.shape
# final = np.matmul(weight, student_scores)
# final

array([[385, 373, 412]])

In [2]:
#Representing the dataset as a matrix
subjects = ['Math', 'English', 'Science']
student1 = [80, 70, 90]
student2 = [60, 85, 75]
student3 = [95, 88, 92]
student4 = [70, 60, 65]

students = np.array([student1, student2, student3, student4])
students

array([[80, 70, 90],
       [60, 85, 75],
       [95, 88, 92],
       [70, 60, 65]])

In [3]:
#Total score per student
# score_for_student1 = np.sum(students[0])
# score_for_student1

total_score= np.sum(students, axis=1)
i=1
for score in total_score:
    print(f"Total score for student {i} is: {score} across {subjects}")
    i+=1


Total score for student 1 is: 240 across ['Math', 'English', 'Science']
Total score for student 2 is: 220 across ['Math', 'English', 'Science']
Total score for student 3 is: 275 across ['Math', 'English', 'Science']
Total score for student 4 is: 195 across ['Math', 'English', 'Science']


In [4]:
#Applying Weights (Scalar Multiplication)
weight = 2

score_weight = students.copy()
score_weight[:,0] = np.dot(weight, score_weight[:,0])
print(f"Updated scores: \n{score_weight}")

Updated scores: 
[[160  70  90]
 [120  85  75]
 [190  88  92]
 [140  60  65]]


In [5]:
#Applying Average score per subject (Matrix Operation)
average_score = np.mean(score_weight, axis=0)

i = 0
for avg in average_score:
    print(f"Average score for {subjects[i]}: is {avg}")
    i+=1


Average score for Math: is 152.5
Average score for English: is 75.75
Average score for Science: is 80.5


In [6]:
#Final grades using matrix mulitplication
weight_vector = [0.5, 0.3, 0.2]
final_grades = np.matmul(students, weight_vector)

i=1
for grade in final_grades:
    print(f"Final grade for student{i}: is {grade}")
    i+=1

Final grade for student1: is 79.0
Final grade for student2: is 70.5
Final grade for student3: is 92.30000000000001
Final grade for student4: is 66.0
