# Case Study: Student Performance Analysis with Linear Algebra

## Step by Step Analysis

## Question 3.1 Representing Data as a Matrix
student_scores = ([[80, 70, 90],
       [60, 85, 75],
       [95, 88, 92],
       [70, 60, 65]])

## Question 3.2 Total Scores per Student (Vector Addition)
Total_score_for_student1 = 80+70+90 = 240

Total_score_for_student2 = 60+85+75 = 220

Total_score_for_student3 = 95+88+92 = 275

Total_score_for_student4 = 70+60+65 = 195

## Question 3.3 Applying Weights (Scalar Multiplication)
weight = 2
math_scores = ([80], [60], [95], [70])

weighted_math_scores = 2*([80], [60], [95], [70])

= ([[160],
       [120],
       [190],
       [140]])
       

## Question 3.4 Average Score per Subject (Matrix Operation)
average_score_for_math = (total_math_score)/(number_of_students)
    =(160+120+190+140)/4
    =(470)/4 = 152.5

average_score_for_english = (total_english_score)/(number_of_students)
    =(70+85+88+60)/4
    =(303)/4 = 75.75

average_score_for_science = (total_science_score)/(number_of_students)
    =(90+75+92+65)/4
    =(322)/4 = 80.5

## Question 3.5 Final Grades using Matrix Multiplication
weight_vector = [0.5, 0.3, 0.2]

final grades = [[(80x0.5), (70x0.3), (90x0.2)],
                [(95x0.5), (85x0.3), (75x0.2)],
                [(95x0.5), (88x0.3), (92x0.2)],
                [(70x0.5), (60x0.3), (65x0.2)]]

final_grades = [[79], 
[70.5], 
[92.3], [66 ]]


## Question 3.6 Comparing Students (Vector Subtraction)
Comparing student 1 and student 4 scores in Maths, English and Science

student1 = [80, 70, 90]

student4 = [70, 60, 65]

comparision = student1 - student4
    = [80-70, 70-60, 90-65]
    = [10, 10, 25]

In [1]:
import numpy as np

In [ ]:
#Question 3.1
#Representing the dataset as a matrix
subjects = ['Math', 'English', 'Science']
student1 = [80, 70, 90]
student2 = [60, 85, 75]
student3 = [95, 88, 92]
student4 = [70, 60, 65]

students = np.array([student1, student2, student3, student4])
students

array([[80, 70, 90],
       [60, 85, 75],
       [95, 88, 92],
       [70, 60, 65]])

In [ ]:
#Question 3.2
#Total score per student
# score_for_student1 = np.sum(students[0])
# score_for_student1

total_score= np.sum(students, axis=1)
i=1
for score in total_score:
    print(f"Total score for student {i} is: {score} across {subjects}")
    i+=1


Total score for student 1 is: 240 across ['Math', 'English', 'Science']
Total score for student 2 is: 220 across ['Math', 'English', 'Science']
Total score for student 3 is: 275 across ['Math', 'English', 'Science']
Total score for student 4 is: 195 across ['Math', 'English', 'Science']


In [ ]:
#Question 3.3
#Applying Weights (Scalar Multiplication)
weight = 2

score_weight = students.copy()
score_weight[:,0] = np.dot(weight, score_weight[:,0])
print(f"Updated scores: \n{score_weight}")

Updated scores: 
[[160  70  90]
 [120  85  75]
 [190  88  92]
 [140  60  65]]


In [ ]:
#Question 3.4
#Applying Average score per subject (Matrix Operation)
average_score = np.mean(score_weight, axis=0)

i = 0
for avg in average_score:
    print(f"Average score for {subjects[i]}: is {avg}")
    i+=1


Average score for Math: is 152.5
Average score for English: is 75.75
Average score for Science: is 80.5


In [ ]:
#Question 3.5
#Final grades using matrix mulitplication
weight_vector = np.array([0.5, 0.3, 0.2])
final_grades = np.matmul(students, weight_vector)

i=1
for grade in final_grades:
    print(f"Final grade for student{i}: is {grade}")
    i+=1

Final grade for student1: is 79.0
Final grade for student2: is 70.5
Final grade for student3: is 92.30000000000001
Final grade for student4: is 66.0


In [ ]:
#Question 3.6
#Comparing Students (Vector Subtraction)
#comparing student 1 and student 4
comparison = np.subtract(student1, student4)
print(f"Difference between student 1 and student 4 scores in Maths, English, and Science: \n{comparison}")


Difference between student 1 and student 4 scores in Maths, English, and Science: 
[10 10 25]


## Add-on Exercises

### Question 1 

In [56]:
subjects = ['Math', 'English', 'Science', 'Economics']

student1 = [80, 70, 90, 81]
student2 = [60, 85, 75, 78]
student3 = [95, 88, 92, 89]
student4 = [70, 60, 65, 79]
student5 = [80, 79, 89, 78]

scores = np.array([student1, student2, student3, student4, student5])

scores

array([[80, 70, 90, 81],
       [60, 85, 75, 78],
       [95, 88, 92, 89],
       [70, 60, 65, 79],
       [80, 79, 89, 78]])

In [61]:
#Total score per student
total_score = np.sum(scores, axis=1)

i = 1
for score in total_score:
    print(f"Total score for student {i} is {score}")
    i+=1

Total score for student 1 is 321
Total score for student 2 is 298
Total score for student 3 is 364
Total score for student 4 is 274
Total score for student 5 is 326


In [65]:
#Average score per student
average = np.mean(scores, axis = 0)

i=0
for avg in average:
    print(f"The average score for {subjects[i]} is {avg}")
    i+=1

#axis = 0 is for columns, axis = 1 is for rows

The average score for Math is 77.0
The average score for English is 76.4
The average score for Science is 82.2
The average score for Economics is 81.0


### Question 2

In [73]:
#Science being 3 times more important than others
science_weight = 3
science_copy = scores.copy()
science_copy[:,2] = np.dot(science_weight, science_copy[:,2])
print(f"Weighted scores \n{science_copy}")

Weighted scores 
[[ 80  70 270  81]
 [ 60  85 225  78]
 [ 95  88 276  89]
 [ 70  60 195  79]
 [ 80  79 267  78]]


In [74]:
#New total scores
new_total_scores = np.sum(science_copy, axis = 1)

i = 1
for new_score in new_total_scores:
    print(f"Total score for student {i} is {new_score}")
    i+=1

Total score for student 1 is 501
Total score for student 2 is 448
Total score for student 3 is 548
Total score for student 4 is 404
Total score for student 5 is 504


### Question 3

In [85]:
#New weights for grading
new_weights = np.array([[0.4], [0.2], [0.3], [0.1]])
weighted_scores = np.matmul(scores, new_weights)
weighted_scores

array([[81.1],
       [71.3],
       [92.1],
       [67.4],
       [82.3]])

### Question 4

In [105]:
#Comparing student 3 and student 4
comparison1 = np.subtract(scores[2,:], scores[3,:])
comparison2 = np.subtract(scores[3,:], scores[2,:])

print(f"Difference between student 3 and student 4 scores: \n Subject\tStu3-Stu4 \tStu4-Stu3 \n{subjects[0]}: \t\t{comparison1[0]} \t\t{comparison2[0]} \n{subjects[1]}: \t{comparison1[1]} \t\t{comparison2[1]} \n{subjects[2]}: \t{comparison1[2]} \t\t{comparison2[2]}\n{subjects[3]}: \t{comparison1[3]} \t\t{comparison2[3]}")
print("Evidently, Student 3 performed better than student 4.")


Difference between student 3 and student 4 scores: 
 Subject	Stu3-Stu4 	Stu4-Stu3 
Math: 		25 		-25 
English: 	28 		-28 
Science: 	27 		-27
Economics: 	10 		-10
Evidently, Student 3 performed better than student 4.
