# Case Study: Student Performance Analysis with Linear Algebra

## Step by Step Analysis

In [1]:
import numpy as np

In [8]:
#Representing the dataset as a matrix
subjects = ['Math', 'English', 'Science']
student1 = [80, 70, 90]
student2 = [60, 85, 75]
student3 = [95, 88, 92]
student4 = [70, 60, 65]

students = np.array([student1, student2, student3, student4])
students

array([[80, 70, 90],
       [60, 85, 75],
       [95, 88, 92],
       [70, 60, 65]])

In [ ]:
#Total score per student
# score_for_student1 = np.sum(students[0])
# score_for_student1

total_score= np.sum(students, axis=1)
i=1
for score in total_score:
    print(f"Total score for student {i} is: {score} across {subjects}")
    i+=1


Total score for student 1 is: 240 across ['Math', 'English', 'Science']
Total score for student 2 is: 220 across ['Math', 'English', 'Science']
Total score for student 3 is: 275 across ['Math', 'English', 'Science']
Total score for student 4 is: 195 across ['Math', 'English', 'Science']


In [31]:
#Applying Weights (Scalar Multiplication)
weight = 2

score_weight = students.copy()
score_weight[:,0] = np.dot(weight, score_weight[:,0])
print(f"Updated scores: \n{score_weight}")

Updated scores: 
[[160  70  90]
 [120  85  75]
 [190  88  92]
 [140  60  65]]


In [43]:
#Applying Average score per subject (Matrix Operation)
average_score = np.mean(score_weight, axis=0)

i = 0
for avg in average_score:
    print(f"Average score for {subjects[i]}: is {avg}")
    i+=1


Average score for Math: is 152.5
Average score for English: is 75.75
Average score for Science: is 80.5
