# CLASS TASK 2

### Question 1

The rows and columsn in each matrices
Matrix A
Matrix A has 2 rows and 3 columns, therefore, matrix A is a 2X3 matrix

Matrix B
Matrix A has 3 rows and 2 columns, therefore matrix B is a 3X2 matrix

### Question 2

The matrix A and B can be multiplied both as AB and BA.
It can be multiplied as AB because the number of columms in matrix A is equal to the number of rows in matrix B
It can also be multiplied as BA because the number of columns in matrix B is equal to the number of rows in matrix A

In [3]:
import numpy as np

In [9]:
matA =np.array([[2,-1,3], [0,4,1]])
matB = np.array([[1,2], [-2, 0], [5, -3]])

computation1 = np.dot(matA,matB)
computation2 = np.dot(matB,matA)

print(f"A X B = \n{computation1}")
print(f"B X A = \n{computation2}")

A X B = 
[[19 -5]
 [-3 -3]]
B X A = 
[[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
