# Class Task 3

### Question A

In [2]:
import numpy as np

In [7]:
matA = np.array([[2, -1], [0, 3]])
matB = np.array([[1, 4], [-2, 5]])

scalar_c = 2
scalar_d = 3

compute1 = np.dot(scalar_c, matA)
compute2 = np.dot(scalar_d, matB)
compute3 = (scalar_c + scalar_d)*matA

print(f"cA = \n{compute1}")
print(f"\ndB = \n{compute2}")
print(f"\n(c+d)A = \n{compute3}")

cA = 
[[ 4 -2]
 [ 0  6]]

dB = 
[[ 3 12]
 [-6 15]]

(c+d)A = 
[[10 -5]
 [ 0 15]]


### Question B


In [11]:
#Associativity of Scalar Multiplication
cA_Computation = np.dot(scalar_c, matA)
Ac_Computation = np.dot(matA, scalar_c)

print(f"Associativity of Scalar Multiplication: {np.array_equal(cA_Computation, Ac_Computation)}")

dB_Computation = np.dot(scalar_d, matB)
Bd_Computation = np.dot(matB, scalar_d)
print(f"Associativity of Scalar Multiplication: {np.array_equal(dB_Computation, Bd_Computation)}")


#Distributivity over Scalar Addition
left =  (scalar_c + scalar_d)*matA

dA_computation = np.dot(scalar_d, matA)
right = cA_Computation + dA_computation 
print(f"Distributivity over Scalar Multiplication: {np.array_equal(left, right)}")


Associativity of Scalar Multiplication: True
Associativity of Scalar Multiplication: True
Distributivity over Scalar Multiplication: True


### Question C

In [13]:
tranposeA = matA.transpose()
tranposeB = matB.transpose()

print(f"Transpose of matrix A: \n{tranposeA}")
print(f"Transpose of matrix B: \n{tranposeB}")

Transpose of matrix A: 
[[ 2  0]
 [-1  3]]
Transpose of matrix B: 
[[ 1 -2]
 [ 4  5]]


### Question D

In [22]:
determinantA = np.linalg.det(matA)
determinantB = np.linalg.det(matB)

print(f"The determinant of matrix A is: {determinantA} \nTherefore matrix A is invertible.")
print(f"\nThe determinant of matrix B is: {determinantB} \nTherefore matrix B is invertible.")


inverseA = np.linalg.inv(matA)
inverseB = np.linalg.inv(matB)
print(f"The inverse of matrix A is: \n {inverseA}")
print(f"\nThe inverse of matrix B is: \n {inverseB}")

The determinant of matrix A is: 6.0 
Therefore matrix A is invertible.

The determinant of matrix B is: 13.0 
Therefore matrix B is invertible.
The inverse of matrix A is: 
 [[0.5        0.16666667]
 [0.         0.33333333]]

The inverse of matrix B is: 
 [[ 0.38461538 -0.30769231]
 [ 0.15384615  0.07692308]]
