# Task 13

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import time

np.set_printoptions(precision=3, suppress=True)

### Question 1

1. Create a 6x6 NumPy array with random integers between 1 and 50. Display the array.

In [9]:
#A 6X6 Numpy array

arr = np.random.randint(50, size=(6,6))
print(f"Random numbers between 1 and 50:\n{arr}")


Random numbers between 1 and 50:
[[ 2 10 34 12 41  3]
 [41 21 48  3 19 36]
 [34  1  7 22 12 31]
 [20 38 37 27 24 15]
 [20  5 49 43 26  6]
 [ 8 42 10 22 28 16]]


### Question 2


2. Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers in the array.


In [10]:
print(f"First 2 rows: \n{arr[0:2, :]}")
print(f"\nLast three columns: \n{arr[:, 3:]}")
print(f"\nEven numbers in the array: \n{arr[arr%2 == 0]}")


First 2 rows: 
[[ 2 10 34 12 41  3]
 [41 21 48  3 19 36]]

Last three columns: 
[[12 41  3]
 [ 3 19 36]
 [22 12 31]
 [27 24 15]
 [43 26  6]
 [22 28 16]]

Even numbers in the array: 
[ 2 10 34 12 48 36 34 22 12 20 38 24 20 26  6  8 42 10 22 28 16]


### Question 3

3. Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D.

In [11]:
#Reshaping into 3D
print(f"Reshaped into 3D:\n{arr.reshape(3,2,6)}")

#Flattening into 1D
flat = arr.flatten()
print(f"\nFlattened: \n{flat}")

Reshaped into 3D:
[[[ 2 10 34 12 41  3]
  [41 21 48  3 19 36]]

 [[34  1  7 22 12 31]
  [20 38 37 27 24 15]]

 [[20  5 49 43 26  6]
  [ 8 42 10 22 28 16]]]

Flattened: 
[ 2 10 34 12 41  3 41 21 48  3 19 36 34  1  7 22 12 31 20 38 37 27 24 15
 20  5 49 43 26  6  8 42 10 22 28 16]


### Question 4

4. Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.

In [12]:
identity = np.eye(4)

np.fill_diagonal(identity, (np.arange(10,50,10)))
print(identity)


[[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 40.]]


### Question 5

5. Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)

In [13]:
#Matrix multiplication
mat1 = np.random.randint(1,10, size=(3,4))
mat2 = np.random.randint(1,10, size=(4,3))
mult = np.dot(mat1,mat2)

print(f"\n3x4 array: \n{mat1}")
print(f"\n4x3 array: \n{mat2}")
print(f"\nMultiplication: \n{mult}")


3x4 array: 
[[9 5 5 1]
 [1 2 5 1]
 [4 4 2 6]]

4x3 array: 
[[3 4 3]
 [4 8 4]
 [3 7 3]
 [2 3 5]]

Multiplication: 
[[ 64 114  67]
 [ 28  58  31]
 [ 46  80  64]]


### Question 6

6. Create a function that takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1.

In [14]:
def array_manipulator(arr2d):
    #this reshapes the inputted 1D array into a 2 by x array
    array = np.array(arr2d).reshape(2,-1)

    #this checks for even numbers and replaces it with the square of that even number or it replaces the odd numbers with -1
    output = np.where(array %2 == 0, array**2, -1 )
    return f"Latest array: \n{output}"

list_array = []
for i in range(4):
    arr2 = int(input("Enter four numbers: "))
    list_array.append(arr2)

print(list_array)
print(array_manipulator(list_array))
    

[1, 1, 1, 1]
Latest array: 
[[-1 -1]
 [-1 -1]]
