# Task 13

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import time

np.set_printoptions(precision=3, suppress=True)

### Question 1

In [7]:
#A 6X6 Numpy array

arr = np.random.randint(50, size=(6,6))
print(f"Random numbers between 1 and 50:\n{arr}")


Random numbers between 1 and 50:
[[12  8 29 23  7  8]
 [49  5 41 34 28 17]
 [31 41 48 41 34 20]
 [28  2 17 14 37 13]
 [ 7 48 45 32 33  2]
 [24 39 35 15 11 31]]


### Question 2

In [ ]:
print(f"First 2 rows: \n{arr[0:2, :]}")
print(f"\nLast three columns: \n{arr[:, 3:]}")
print(f"Even numbers in the array: \n{arr[arr%2 == 0]}")


First 3 rows: 
[[12  8 29 23  7  8]
 [49  5 41 34 28 17]
 [31 41 48 41 34 20]]

Last three columns: 
[[23  7  8]
 [34 28 17]
 [41 34 20]
 [14 37 13]
 [32 33  2]
 [15 11 31]]
Even numbers in the array: 
[12  8  8 34 28 48 34 20 28  2 14 48 32  2 24]


### Question 3

In [9]:
#Reshaping into 3D
print(f"Reshaped into 3D:\n{arr.reshape(3,2,6)}")

#Flattening into 1D
flat = arr.flatten()
print(f"\nFlattened: \n{flat}")

Reshaped into 3D:
[[[12  8 29 23  7  8]
  [49  5 41 34 28 17]]

 [[31 41 48 41 34 20]
  [28  2 17 14 37 13]]

 [[ 7 48 45 32 33  2]
  [24 39 35 15 11 31]]]

Flattened: 
[12  8 29 23  7  8 49  5 41 34 28 17 31 41 48 41 34 20 28  2 17 14 37 13
  7 48 45 32 33  2 24 39 35 15 11 31]


### Question 4

In [10]:
identity = np.eye(4)

np.fill_diagonal(identity, (np.arange(10,50,10)))
print(identity)


[[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 40.]]


### Question 5

In [11]:
#Matrix multiplication
mat1 = np.random.randint(1,10, size=(3,4))
mat2 = np.random.randint(1,10, size=(4,3))
mult = np.dot(mat1,mat2)

print(f"\n3x4 array: \n{mat1}")
print(f"\n4x3 array: \n{mat2}")
print(f"\nMultiplication: \n{mult}")


3x4 array: 
[[1 4 9 1]
 [4 3 5 4]
 [7 9 9 3]]

4x3 array: 
[[5 9 6]
 [4 4 9]
 [2 5 5]
 [2 7 7]]

Multiplication: 
[[ 41  77  94]
 [ 50 101 104]
 [ 95 165 189]]


### Question 6

In [25]:
def array_manipulator(arr2d):
    #this reshapes the inputted 1D array into a 2 by x array
    array = np.array(arr2d).reshape(2,-1)

    #this checks for even numbers and replaces it with the square of that even number or it replaces the odd numbers with -1
    output = np.where(array %2 == 0, array**2, -1 )
    return f"Latest array: \n{output}"

list_array = []
for i in range(4):
    arr2 = int(input("Enter four numbers: "))
    list_array.append(arr2)

print(list_array)
print(array_manipulator(list_array))
    

[2, 3, 4, 5]
Latest array: 
[[ 4 -1]
 [16 -1]]
